import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "BuckIT",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col md:flex-row md:overflow-hidden">
      <div className="w-full flex-none md:w-64">
        BUCKIT
      </div>
      <div className="flex-grow p-6 md:p-12">{children}</div>
    </div>
  );
}
