import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Link from 'next/link'


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "BuckIT",
//   description: "Generated by create next app",
// };

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full grid min-[700px]:grid-cols-3 min-[1000px]:grid-cols-2">
      <div className="place-items-center max-[700px]:hidden">
        BUCKIT
      </div>
      <div className="content-center min-[700px]:col-span-2 min-[1000px]:col-span-1 p-6 md:p-12">{children}</div>
    </div>
  );
}
