// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/26/2024, 3:37:53 PM
const configMerger = require("C:/Users/soga2/Documents/Projects/buckit/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/soga2/Documents/Projects/buckit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/plugins/**/*.{js,ts,mjs}","C:/Users/soga2/Documents/Projects/buckit/composables/**/*.{js,ts,mjs}","C:/Users/soga2/Documents/Projects/buckit/utils/**/*.{js,ts,mjs}","C:/Users/soga2/Documents/Projects/buckit/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/soga2/Documents/Projects/buckit/app.config.{js,ts,mjs}"] }));

module.exports = config
